application:
    port: 8111
    threaded: true
    secret_key: 'secret_key'
database:
    user: test
    pass: Devpass123
    host: localhost
    name: giftsmarts
facebook:
    id: '1670209469887605'
    name: GiftSmarts
    secret: 65c27afa66f17051324f3a64243c7133